### PR TITLE
Support 1.19.2

### PR DESCRIPTION
**Pull request by isning**
Only tested on 1.19.2, maybe I'm in lack of luck??? I didn't encounter any blossom tree, this may also be a bug. Others' work well.

P.S.I think this should be pushed to 1.19.2 branch, but there's no one exists, sry~

### CODE REVIEW

**Comment by Harleyoc1** [comment]
What is the reasoning behind de3e61ccf587856ff822c98482b0f02f4ec5b8d4?

**Comment by isning** [comment]
Sorry, but I didn't remember exactly why  I have done that, I think it might be it caused some exceptions, maybe something related to worldgen because of lack of something for glowshroom?

**Comment by Harleyoc1** [comment]
This isn't quite correct, `type` is no longer a valid selector (as biome dictionary was removed) so the trees will be applied to every biome.

I'm going to just merge it anyway and update the worldgen myself.

**Comment by isning** [comment]
Oh, I didn't notice that

**Pull request merged**
